name: SOS Integration Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # Actualizamos a la versión que te pide el error
      image: mcr.microsoft.com/playwright:v1.49.1-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          cd src/front && npm install --legacy-peer-deps

      - name: Run API tests
        run: npm test

      - name: Run Playwright tests
        run: |
          npm start &
          # Esperamos a que el puerto 10000 esté libre/listo
          sleep 10
          npx playwright test

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30